language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: NUvTFD1TV1YDiUOOLWccSB4agQqd2m5ePEzHqwBLw7Uv8IZ9Bs2XmaYYThLtlJucqprN+DkZ8u2goai33U+QRAG73YQ92w9oiRQvuu3mfO6saJPe1VK4JKiTfZU34bFx/qx/xWL00PXjGfiNbD2qLSPLi8fDcytZd4lczDqfitMZqHH7Ref4jcz7tMb1ZayKf1cywBZgEG05sOuCgx0s6mxQu08MoCS9MubBmGTye1NhXTjLV3J0w0pc7oZ/52mLJUlpgkVukZ4CFDKytkJH25wHVAaHxFa262L8E2miIh+j5SSXatLbtwOwqtoYmxeet1WLSxz0rcpVUX9qu8hbjyxa+tmzy88lfHlwZWp/Pv8VxJ7ub8GPnregOYg3ksNKeIJbWufqWdTClTA3WZ3ZvXh4mVd0P7Uf6taifL1WjhvnkI32+z02Cg/OS74jaQRCoqUl1R1/kj38+mME/vImnD93/6CLOO4yVYuZXnebiZoqBo2JMUafhcSQbDUM2wLVc59vrw7pvaZzjDIRvaC4FfblKW/GADpHl4iIF1Rfgyl2Wn9RDmQIFLkc3vas1sOXFrMK6dJH8MGHuc7AwIX1FSBI8ZqoZHZvic/kDv1KdcwO7sbBKhxhmQJlVxk1FDFWEXscPyMeB9rhoD+WJeZimxhjHA5sDAFd6ItEpKOrCwU=
  app: cryptocoinkeeper
  on:
    repo: Schmerb/cryptokeeper-api
